export const actionTypes = {
	LOAD_DATA_IN_STORE: 'LOAD_DATA_IN_STORE',
	UPDATE_DATA_IN_STORE: 'UPDATE_DATA_IN_STORE',
	LOAD_DATA_IN_STORE_ASYNC: 'LOAD_DATA_IN_STORE_ASYNC',
	UPDATE_DATA_IN_STORE_ASYNC: 'UPDATE_DATA_IN_STORE_ASYNC',
	NEXT_PAGE: "NEXT_PAGE",
	PREV_PAGE: "PREV_PAGE",
};
